/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const computed: typeof import('vue')['computed']
  const getMetadata: typeof import('./utils/utils.js')['getMetadata']
  const getVariable: typeof import('./utils/utils.js')['getVariable']
  const isMenuOpen: typeof import('./store/menu')['isMenuOpen']
  const onMounted: typeof import('vue')['onMounted']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const ref: typeof import('vue')['ref']
  const watch: typeof import('vue')['watch']
}
