/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const activeSection: typeof import('./store/menu')['activeSection']
  const activeSubsection: typeof import('./store/menu')['activeSubsection']
  const camelize: typeof import('./utils/utils.js')['camelize']
  const computed: typeof import('vue')['computed']
  const evilDOMHack: typeof import('./utils/utils')['evilDOMHack']
  const expectedNavColor: typeof import('./store/menu')['expectedNavColor']
  const getMetadata: typeof import('./utils/utils')['getMetadata']
  const getVariable: typeof import('./utils/utils')['getVariable']
  const isMenuOpen: typeof import('./store/menu')['isMenuOpen']
  const navColor: typeof import('./store/menu')['navColor']
  const onMounted: typeof import('vue')['onMounted']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const pascalize: typeof import('./utils/utils')['pascalize']
  const ref: typeof import('vue')['ref']
  const sections: typeof import('./utils/utils')['sections']
  const smallNavColor: typeof import('./store/menu')['smallNavColor']
  const watch: typeof import('vue')['watch']
}
