/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const activeSection: typeof import('./store/menu')['activeSection']
  const activeSubsection: typeof import('./store/menu')['activeSubsection']
  const camelize: typeof import('./utils/utils.js')['camelize']
  const computed: typeof import('vue')['computed']
  const evilDOMHack: typeof import('./utils/utils')['evilDOMHack']
  const expectednavTheme: typeof import('./store/menu')['expectednavTheme']
  const getMetadata: typeof import('./utils/utils')['getMetadata']
  const getVariable: typeof import('./utils/utils')['getVariable']
  const isMenuOpen: typeof import('./store/menu')['isMenuOpen']
  const navTheme: typeof import('./store/menu')['navTheme']
  const onMounted: typeof import('vue')['onMounted']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const pascalize: typeof import('./utils/utils')['pascalize']
  const ref: typeof import('vue')['ref']
  const sections: typeof import('./utils/utils')['sections']
  const smallNavTheme: typeof import('./store/menu')['smallNavTheme']
  const watch: typeof import('vue')['watch']
}
